name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up MPI
      run: sudo apt-get install -y mpich
    - name: Install dependencies
      run: sudo apt-get install -y cmake g++
    - name: Configure
      run: cmake .
    - name: Build
      run: cmake --build .
    - name: Run tests
      run: ctest --output-on-failure

  build-singularity:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    - uses: actions/checkout@v2
    - name: Install Singularity
      run: |
        sudo apt-get update
        sudo apt-get install -y singularity-container
    - name: Build Singularity image
      run: |
        singularity build matrix_multiplication.sif Singularity.def
    - name: Upload Singularity image
      uses: actions/upload-artifact@v2
      with:
        name: matrix_multiplication.sif
        path: matrix_multiplication.sif

